name: lms
description: 'A learning management system build with Flutter'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  # firebase_analytics: ^11.3.3
  # firebase_cloud_firestore: ^5.4.4
  # firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
