name: lms
description: 'A learning management system build with Flutter'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  # Firebase & Firefuel
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firefuel: ^0.4.5 
  
  # UI & State Management
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  font_awesome_flutter: ^10.10.0
  
  # Video Player
  video_player: ^2.10.0
  chewie: ^1.13.0
  
  # Other
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/svgs/
