// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXM8JPMyR_MZS8zKuAgTIYeoj-LVWGR_o',
    appId: '1:698709584913:web:3a4b394ea85ce4839515b0',
    messagingSenderId: '698709584913',
    projectId: 'coursify-lms',
    authDomain: 'coursify-lms.firebaseapp.com',
    storageBucket: 'coursify-lms.firebasestorage.app',
    measurementId: 'G-R6CECQFX4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALZJV1V1jI3Ll3i3Eb_sYZOB5NOnA-6mo',
    appId: '1:698709584913:android:0afaffa21f68701f9515b0',
    messagingSenderId: '698709584913',
    projectId: 'coursify-lms',
    storageBucket: 'coursify-lms.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd1U15G132w0r9KEFS4mGNNdbxe6LHkQI',
    appId: '1:698709584913:ios:d320007f7983df159515b0',
    messagingSenderId: '698709584913',
    projectId: 'coursify-lms',
    storageBucket: 'coursify-lms.firebasestorage.app',
    iosBundleId: 'com.supposedlysam.lms',
  );
}
